Failure # 1 (occurred at 2025-04-25_14-43-19)
[36mray::ImplicitFunc.train()[39m (pid=50268, ip=10.33.20.59, actor_id=40c42f2a00e02cb5b0ae36ff01000000, repr=tune_train_func)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 330, in train
    raise skipped from exception_cause(skipped)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 107, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 261, in _trainable_func
    output = fn()
  File "/home/shyam/PycharmProjects/Softmax/train.py", line 108, in tune_train_func
    outputs = model(x)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/shyam/PycharmProjects/Softmax/models.py", line 36, in forward
    x = self.feature_extractor(x)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 375, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 370, in _conv_forward
    return F.conv1d(
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [16, 4, 2, 100, 100]
